### PR TITLE
Fix: linked tasks colour

### PR DESCRIPTION
**Pull request by vladimir-8**
- Integrated the latest version of the https://github.com/coopcycle/coopcycle-frontend-js library (using https://github.com/ingydotnet/git-subrepo)
- Fixed: https://github.com/coopcycle/coopcycle-app/issues/1455

### CODE REVIEW

**Review by r0xsh — COMMENTED** [review]
Thank you for contribution and proposing changes. However, there is a minor adjustment needed in the pull request. Instead of using git submodule, we need to update the version of the `coopcycle-frontend-js` in package.json. Apart from that, everything else looks good. Excellent job, and thank you once again!

See: https://docs.npmjs.com/cli/v9/configuring-npm/package-json#git-urls-as-dependencies

**Comment by vladimir-8** [comment]
Thanks for the review! 

That's on purpose, actually. I remember discussing it with @alexsegura at some point. We concluded that it is way easier to develop a library when the code is in the same folder rather than releasing a new version and importing it as a dependency in package.json. The same approach is used in [github.com/coopcycle/coopcycle-web/](https://github.com/coopcycle/coopcycle-web/) If sticking to this approach, it could be removed from package.json dependencies.

**Comment by vladimir-8** [comment]
Great! Thanks for reviewing @lucasferraro! Will you merge it, or should I?

**Comment by lucasferraro** [comment]
> Great! Thanks for reviewing @lucasferraro! Will you merge it, or should I?

Merged ;)

**Pull request merged**
