### PR TITLE
Fix search crash

### PR DESCRIPTION
**Pull request by r0xsh**

### CODE REVIEW

**Comment by vladimir-8** [comment]
While this PR fixes the crash, I think we should create another issue to actually allow a customer to open all found restaurants and products from the search results, and not only the ones that we have in the redux

**Review by vladimir-8 — APPROVED** [review]
While this PR fixes the crash, I think we should create another issue to actually allow a customer to open all found restaurants and products from the search results, and not only the ones that we have in the redux

**Comment by alexsegura** [comment]
I removed the "Fixes"

**Comment by r0xsh** [comment]
> While this PR fixes the crash, I think we should create another issue to actually allow a customer to open all found restaurants and products from the search results, and not only the ones that we have in the redux

Initially, I solved the problem by lazy loading the restaurant information. But then, I noticed it's strange to display a restaurant where you can't place an order. If this is what we want, we need to change the Restaurant page to prevent order creation. Because, as I experienced yesterday, when you try to place an order, the app immediately tells you that delivery isn't possible, which is odd.

**Comment by r0xsh** [comment]
Or maybe show all the restaurants in search results but the one that can't be ordered from are disabled (like putting them in a grey color)

**Pull request merged**
